import {Montserrat} from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import {StoreProvider} from "@/Store/StoreProvider";
import {Provider} from "react-redux";
import Providers from "@/app/Providers";


const montserrat = Montserrat({subsets: ["latin"]});


export const metadata = {
    title: "Ekhonni",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {

    return (
        <StoreProvider>
            <html lang="en">
            <body className={montserrat.className}>
            <Providers>{children}</Providers>
            <Footer/>
            </body>
            </html>
        </StoreProvider>
    );
}
