import {Montserrat} from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import {StoreProvider} from "@/Store/StoreProvider";
import SessionProvider from "@/components/SessionProvider";
import {getServerSession} from "next-auth";
import Providers from "@/utils/Providers";

const montserrat = Montserrat({subsets: ["latin"]});


export const metadata = {
    title: "Ekhonni",
    description: "Generated by create next app",
};

export default async function RootLayout({children}) {

    const session = await getServerSession();
    return (
        <StoreProvider>
            <html lang="en">
            <body className={montserrat.className}>
                <SessionProvider session={session}>
                    <Providers>
                        {children}
                    </Providers>
                </SessionProvider>
            <Footer/>
            </body>
            </html>
        </StoreProvider>
    );
}
