export const ADD_CATEGORY_FILTER = "add category filter"
export const ADD_SUBCATEGORY_FILTER = "add subcategory filter"
export const ADD_DIVISION_FILTER = "add division filter"
export const ADD_PRICE_FILTER = "add price filter"
export const ADD_SORT_FILTER = "add sorting filter"
export const CLEAR_ALL_FILTER = "clear all filter"
export const DELETE_INDIVIDUAL_PRODUCT = "delete individual product"
export const PRODUCT_REQUEST = "product request"
export const PRODUCT_SUCCESSFULLY_FETCH = "product successfully fetch"
export const PRODUCT_FETCH_ERROR = "can't fetch the product"
export const SEARCH_PRODUCT = "search product"
export const UPDATE_PAGE = "update page"

